SET SCHEMA FN000;

CREATE VIEW FN000.POSTS_SUMMARY_VIEW
  AS
SELECT P.POST_ID, U.FIRST_NAME || ' ' || U.LAST_NAME AS "USER NAME", P.LIKES, P.COMMENTS
FROM FN000.POSTS AS P, FN000.USERS AS U
WHERE P.POSTER_ID = U.USER_ID;


CREATE VIEW FN000.EVENTS_SUMMARY_VIEW
  AS
SELECT E.HOST_ID, U.FIRST_NAME || ' ' || U.LAST_NAME AS "USER NAME", E.GOING_COUNT, E.INTERESTED_COUNT
FROM FN000.EVENTS AS E, FN000.USERS AS U
WHERE E.HOST_ID = U.USER_ID;

