SET SCHEMA FN000;

CREATE TABLE IMAGES (
  IMAGE_ID INTEGER PRIMARY KEY NOT NULL,
  IMAGE_URI VARCHAR (1000)     NOT NULL,
  DESCRIPTION CLOB
);

CREATE TABLE USERS (
	USER_ID INTEGER PRIMARY KEY     NOT NULL,
	FIRST_NAME VARCHAR(20) 			    NOT NULL,
	LAST_NAME VARCHAR(20) 			    NOT NULL,
	EMAIL VARCHAR(30) 					    NOT NULL,
	DATE_OF_BIRTH DATE 			  	    NOT NULL,
  SEX CHAR(1)                     NOT NULL,
	PROFILE_PHOTO_ID INTEGER,
	COVER_PHOTO_ID INTEGER
);

ALTER TABLE USERS
    ADD CONSTRAINT PROFILE_PHOTO_FK FOREIGN KEY (PROFILE_PHOTO_ID)
      REFERENCES IMAGES (IMAGE_ID)
      ON DELETE CASCADE
    ADD CONSTRAINT COVER_PHOTO_FK FOREIGN KEY (COVER_PHOTO_ID)
      REFERENCES IMAGES (IMAGE_ID)
      ON DELETE CASCADE;

CREATE TABLE FRIENDSHIPS (
	USER1_ID INTEGER 														 NOT NULL,
	USER2_ID INTEGER 													   NOT NULL,
	DATE_OF_FRIENDSHIP DATE DEFAULT CURRENT_DATE NOT NULL
);

ALTER TABLE FRIENDSHIPS
	ADD PRIMARY KEY (USER1_ID, USER2_ID)
	ADD CONSTRAINT USER1_FK FOREIGN KEY (USER1_ID)
    REFERENCES USERS (USER_ID)
    ON DELETE CASCADE
	ADD CONSTRAINT USER2_FK FOREIGN KEY (USER2_ID)
    REFERENCES USERS (USER_ID)
    ON DELETE CASCADE;

CREATE TABLE POSTS (
	POST_ID INTEGER PRIMARY KEY 										 NOT NULL,
	DESCRIPTION CLOB 																 NOT NULL,
	PUBLISH_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	LIKES INTEGER DEFAULT 0 												 NOT NULL,
	COMMENTS INTEGER DEFAULT 0 											 NOT NULL,
	POST_PHOTO_ID INTEGER,
  POSTER_ID INTEGER                                NOT NULL
);

ALTER TABLE POSTS
  ADD CONSTRAINT POSTER_FK FOREIGN KEY (POSTER_ID)
    REFERENCES USERS (USER_ID)
    ON DELETE CASCADE
  ADD CONSTRAINT POST_PHOTO_FK FOREIGN KEY (POST_PHOTO_ID)
      REFERENCES IMAGES (IMAGE_ID)
      ON DELETE CASCADE;

CREATE TABLE LIKES (
	USER_ID INTEGER NOT NULL,
	POST_ID INTEGER NOT NULL
);

ALTER TABLE LIKES
	ADD PRIMARY KEY (USER_ID, POST_ID)
	ADD CONSTRAINT USER_FK FOREIGN KEY (USER_ID)
		REFERENCES USERS (USER_ID)
		ON DELETE CASCADE
	ADD CONSTRAINT POST_FK FOREIGN KEY (POST_ID)
    REFERENCES POSTS (POST_ID)
    ON DELETE CASCADE;

CREATE TABLE COMMENTS (
	USER_ID INTEGER 				 NOT NULL,
	POST_ID INTEGER 				 NOT NULL,
	DESCRIPTION VARCHAR(200) NOT NULL
);

ALTER TABLE COMMENTS
	ADD PRIMARY KEY (USER_ID, POST_ID)
	ADD CONSTRAINT USER_FK FOREIGN KEY (USER_ID)
    REFERENCES USERS (USER_ID)
    ON DELETE CASCADE
	ADD CONSTRAINT POST_FK FOREIGN KEY (POST_ID)
    REFERENCES POSTS (POST_ID)
    ON DELETE CASCADE;

CREATE TABLE EVENTS (
	EVENT_ID INTEGER PRIMARY KEY 		 	 NOT NULL,
	NAME VARCHAR(30) 								   NOT NULL,
	DESCRIPTION CLOB 									 NOT NULL,
	EVENT_DATE TIMESTAMP 							 NOT NULL,
	GOING_COUNT INTEGER DEFAULT 0 		 NOT NULL,
	INTERESTED_COUNT INTEGER DEFAULT 0 NOT NULL,
  EVENT_COVER_PHOTO_ID INTEGER,
  HOST_ID INTEGER                    NOT NULL
);

ALTER TABLE EVENTS
  ADD CONSTRAINT HOST_FK FOREIGN KEY (HOST_ID)
    REFERENCES USERS (USER_ID)
    ON DELETE CASCADE
  ADD CONSTRAINT EVENT_COVER_PHOTO_FK FOREIGN KEY (EVENT_COVER_PHOTO_ID)
      REFERENCES IMAGES (IMAGE_ID)
      ON DELETE CASCADE;

CREATE TABLE EVENT_ACTIVITY (
	EVENT_ID INTEGER       NOT NULL,
	USER_ID INTEGER        NOT NULL,
	IS_GOING SMALLINT      NOT NULL,
	IS_INTERESTED SMALLINT NOT NULL
);

ALTER TABLE EVENT_ACTIVITY
  ADD CONSTRAINT EVENT_ACT_PK PRIMARY (EVENT_ID, USER_ID)
  ADD CONSTRAINT EVENT_FK FOREIGN KEY (EVENT_ID)
    REFERENCES EVENTS (EVENT_ID)
    ON DELETE CASCADE
  ADD CONSTRAINT USER_FK FOREIGN KEY (USER_ID)
      REFERENCES USERS (USER_ID)
      ON DELETE CASCADE;