SET SCHEMA FN000;

CREATE TRIGGER AFTER_INSERT_LIKES_RECORD_INC_POST_COUNTER_TRIG
  AFTER INSERT ON FN000.LIKES
  REFERENCING NEW AS NEW_LIKE_RECORD
  FOR EACH ROW
  BEGIN ATOMIC
    UPDATE FN000.POSTS AS P
      SET P.LIKES = P.LIKES + 1
    WHERE P.POST_ID = NEW_LIKE_RECORD.POST_ID;
  END;

CREATE TRIGGER AFTER_DELETE_LIKES_RECORD_DECR_POST_COUNTER_TRIG
  AFTER DELETE ON FN000.LIKES
  REFERENCING OLD AS OLD_LIKE_RECORD
  FOR EACH ROW
  BEGIN ATOMIC
    UPDATE FN000.POSTS AS P
      SET P.LIKES = P.LIKES - 1
    WHERE P.POST_ID = OLD_LIKE_RECORD.POST_ID;
  END;


CREATE TRIGGER AFTER_INSERT_COMMENTS_RECORD_INC_POST_COUNTER_TRIG
  AFTER INSERT ON FN000.COMMENTS
  REFERENCING NEW AS NEW_COMMENT_RECORD
  FOR EACH ROW
  BEGIN ATOMIC
    UPDATE FN000.POSTS AS P
      SET P.COMMENTS = P.COMMENTS + 1
    WHERE P.POST_ID = NEW_COMMENT_RECORD.POST_ID;
  END;

CREATE TRIGGER AFTER_DELETE_COMMENTS_RECORD_DECR_POST_COUNTER_TRIG
  AFTER DELETE ON FN000.COMMENTS
  REFERENCING OLD AS OLD_COMMENT_RECORD
  FOR EACH ROW
  BEGIN ATOMIC
    UPDATE FN000.POSTS AS P
      SET P.COMMENTS = P.COMMENTS - 1
    WHERE P.POST_ID = OLD_COMMENT_RECORD.POST_ID;
  END;


CREATE TRIGGER AFTER_INSERT_EVENT_ACTIVITY_RECORD_INC_EVENT_COUNTER_TRIG
  AFTER INSERT ON FN000.EVENT_ACTIVITY
  REFERENCING NEW AS NEW_EVENT_ACT_RECORD
  FOR EACH ROW
  BEGIN ATOMIC
    IF NEW_EVENT_ACT_RECORD.IS_GOING = 1
    THEN
        UPDATE FN000.EVENTS AS E
          SET E.GOING_COUNT = E.GOING_COUNT + 1
        WHERE E.EVENT_ID = NEW_EVENT_ACT_RECORD.EVENT_ID;
    ELSE
      UPDATE FN000.EVENTS AS E
          SET E.INTERESTED_COUNT = E.INTERESTED_COUNT + 1
      WHERE E.EVENT_ID = NEW_EVENT_ACT_RECORD.EVENT_ID;
      END IF;
  END;

CREATE TRIGGER AFTER_DELETE_EVENT_ACTIVITY_RECORD_DECR_EVENT_COUNTER_TRIG
  AFTER DELETE ON FN000.EVENT_ACTIVITY
  REFERENCING OLD AS OLD_EVENT_ACT_RECORD
  FOR EACH ROW
  BEGIN ATOMIC
    IF OLD_EVENT_ACT_RECORD.IS_GOING = 1
    THEN
        UPDATE FN000.EVENTS AS E
          SET E.GOING_COUNT = E.GOING_COUNT - 1
        WHERE E.EVENT_ID = OLD_EVENT_ACT_RECORD.EVENT_ID;
    ELSE
      UPDATE FN000.EVENTS AS E
          SET E.INTERESTED_COUNT = E.INTERESTED_COUNT - 1
      WHERE E.EVENT_ID = OLD_EVENT_ACT_RECORD.EVENT_ID;
      END IF;
  END;