SET SCHEMA FN000;

CREATE FUNCTION FN000.RETRIEVE_SCHEDULE_FOR_DATE(V_FLIGHT_DATE DATE)
  RETURNS TABLE (FLIGHT_NUMBER SMALLINT, FLIGHT_DATE DATE, "DEPARTURE LOCATION" VARCHAR(50), "DEPARTURE TIME" TIME, "ARRIVING LOCATION" VARCHAR(50), "ARRIVAL TIME" TIME)
  RETURN
  SELECT F.FLIGHT_NUMBER, F.FLIGHT_DATE, S.DEPT_CITY || ', ' || S.DEPT_COUNTRY || ' (' || S.DEPT_AIRPORT || ')', S.DEPT_TIME,
    S.ARRV_CITY || ', ' || S.ARRV_COUNTRY || ' (' || S.ARRV_AIRPORT || ')', S.ARRV_TIME
  FROM FLIGHTS F, SCHEDULES S
  WHERE F.FLIGHT_NUMBER = S.FLIGHT_NUMBER
  AND F.FLIGHT_DATE = V_FLIGHT_DATE;

/* Demonstration:
SELECT *
  FROM TABLE(FN000.RETRIEVE_SCHEDULE_FOR_DATE('2012-05-23'));
*/

CREATE FUNCTION FN000.CALC_PASSENGERS_FOR_DATE_PERIOD(V_AIRLINE_CODE CHAR(2), V_START_DATE DATE, V_END_DATE DATE)
  RETURNS INTEGER
  RETURN
  SELECT COUNT(*)
  FROM FLIGHTS AS F, BOOKINGS AS B
  WHERE F.FLIGHT_NUMBER = B.FLIGHT_NUMBER
    AND F.AIRLINE_CODE = V_AIRLINE_CODE
    AND F.FLIGHT_DATE BETWEEN V_START_DATE AND V_END_DATE;

/* Demonstration:
SELECT FN000.CALC_PASSENGERS_FOR_DATE_PERIOD('AA', '1990-01-01', CURRENT_DATE)
FROM FLIGHTS
FETCH FIRST ROW ONLY;
*/

CREATE FUNCTION FN000.GET_LAST_MONTH_DATE()
RETURNS DATE
RETURN
SELECT(DATE('0001-01-01') + (YEAR(CURRENT_DATE - 1 MONTH) - 1) YEARS)
+ (MONTH (CURRENT_DATE - 1 MONTH) - 1 ) MONTHS
from SYSIBM.SYSDUMMY1;


CREATE VIEW FN000.FLIGHT_SUMMARY_VIEW
  AS
SELECT A.NAME AS "AIRLINE NAME", DAILY_SCHEDULE.FLIGHT_NUMBER, DAILY_SCHEDULE.FLIGHT_DATE,
  DAILY_SCHEDULE."DEPARTURE LOCATION", DAILY_SCHEDULE."DEPARTURE TIME",
  DAILY_SCHEDULE."ARRIVING LOCATION", DAILY_SCHEDULE."ARRIVAL TIME",
  FN000.CALC_PASSENGERS_FOR_DATE_PERIOD('AA', FN000.GET_LAST_MONTH_DATE(), FN000.GET_LAST_MONTH_DATE() + 1 MONTH - 1 DAY) AS "PREVIOUS MONTH PASSENGER COUNT"
FROM TABLE(FN000.RETRIEVE_SCHEDULE_FOR_DATE(CURRENT_DATE)) AS DAILY_SCHEDULE, FLIGHTS AS F, AIRLINES AS A
WHERE DAILY_SCHEDULE.FLIGHT_NUMBER = F.FLIGHT_NUMBER
  AND F.AIRLINE_CODE = A.CODE;

/* Demontration:
  SELECT *
  FROM FN000.FLIGHT_SUMMARY_VIEW;
*/
