SET SCHEMA FN000@

/* Stored Procedure 1: */
CREATE PROCEDURE FN000.AIRLINE_INFORMATION_SP
			(IN CODE CHAR(2))
RESULT SETS 3
LANGUAGE SQL
BEGIN
	DECLARE C1 CURSOR WITH RETURN TO CLIENT FOR
		SELECT *
		FROM FN000.SCHEDULES
		WHERE AIRLINE_CODE = CODE;
	DECLARE C2 CURSOR WITH RETURN TO CLIENT FOR
		SELECT *
		FROM FN000.FLIGHTS
		WHERE AIRLINE_CODE = CODE;
	DECLARE C3 CURSOR WITH RETURN TO CLIENT FOR
		SELECT *
		FROM FN000.BOOKINGS
		WHERE AIRLINE_CODE = CODE;

	OPEN C1;
	OPEN C2;
	OPEN C3;
END@

CALL FN000.AIRLINE_INFORMATION_SP('AA')@

-- DROP PROCEDURE FN000.AIRLINE_INFORMATION_SP@


/* Stored Procedure 2: */
CREATE PROCEDURE FN000.DAILY_FLIGHTS_PER_COUNTRY_SP
			(IN DATE_PARAM DATE,
			 IN COUNTRY_PARAM CHAR(2))
RESULT SET 1
LANGUAGE SQL
BEGIN
	DECLARE C1 CURSOR WITH RETURN TO CLIENT FOR
		SELECT A.NAME, TBL.*
		FROM FN000.AIRLINES A, FN000.SCHEDULES S,
			(SELECT *
			 FROM  TABLE (FN000.RETRIEVE_SCHEDULE_FOR_DATE(DATE_PARAM)) ) AS TBL
		WHERE A.CODE = S.AIRLINE_CODE
			AND TBL.FLIGHT_NUMBER = S.FLIGHT_NUMBER
			AND S.DEPT_COUNTRY = COUNTRY_PARAM;
	OPEN C1;
END@

CALL FN000.DAILY_FLIGHTS_PER_COUNTRY_SP('2012-05-23','US')@

-- DROP PROCEDURE FN000.DAILY_FLIGHTS_PER_COUNTRY_SP@

/* Stored Procedure 3: */
CREATE FUNCTION FN000.GET_CUSTOMER_BOOKINGS_COUNT(CUST_NAME VARCHAR(50))
RETURNS INTEGER
RETURN
  SELECT COUNT(BOOKING_NUMBER)
  FROM FN000.BOOKINGS
  WHERE CUSTOMER_NAME = CUST_NAME
  	AND CUSTOMER_NAME IS NOT NULL@

CREATE FUNCTION FN000.GET_CUSTOMER_BOOKINGS_COUNT_FOR_PERIOD(CUST_NAME VARCHAR(50))
RETURNS INTEGER
RETURN
  SELECT COUNT(BOOKING_NUMBER)
  FROM FN000.BOOKINGS
  WHERE ORDER_DATE BETWEEN '2012-01-01' AND '2012-12-31'
		AND CUSTOMER_NAME = CUST_NAME
		AND CUSTOMER_NAME IS NOT NULL@

CREATE PROCEDURE FN000.CUSTOMER_INFORMATION_SP
			(IN FLIGHT_NUM_PARAM INTEGER)
RESULT SET 2
LANGUAGE SQL
BEGIN
	DECLARE C1 CURSOR WITH RETURN TO CLIENT FOR
		SELECT DISTINCT CUSTOMER_NAME
		FROM FN000.BOOKINGS
		WHERE FLIGHT_NUMBER = FLIGHT_NUM_PARAM;
	DECLARE C2 CURSOR WITH RETURN TO CLIENT FOR
		SELECT DISTINCT B.CUSTOMER_NAME, A.NAME, FN000.GET_CUSTOMER_BOOKINGS_COUNT(B.CUSTOMER_NAME) AS CUSTOMER_BOOKINGS_COUNT
		FROM FN000.BOOKINGS B, FN000.AIRLINES A
		WHERE B.FLIGHT_NUMBER = FLIGHT_NUM_PARAM
			AND A.CODE = B.AIRLINE_CODE
			AND FN000.GET_CUSTOMER_BOOKINGS_COUNT_FOR_PERIOD(B.CUSTOMER_NAME) >= 2;
	OPEN C1;
	OPEN C2;
END@

CALL FN000.CUSTOMER_INFORMATION_SP(1000)@

-- DROP PROCEDURE FN000.CUSTOMER_INFORMATION_SP@